###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := x86_64_quanta_ly8_rangeley_r0
AUTOMODULE := x86_64_quanta_ly8_rangeley_r0
include $(BUILDER)/definemodule.mk
