
###############################################################################
#
# Inclusive Makefile for the x86_64_quanta_ly8_rangeley_r0 module.
#
# Autogenerated 2016-01-05 16:19:11.760587
#
###############################################################################
x86_64_quanta_ly8_rangeley_r0_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_quanta_ly8_rangeley_r0_BASEDIR)/module/make.mk
include $(x86_64_quanta_ly8_rangeley_r0_BASEDIR)/module/auto/make.mk
include $(x86_64_quanta_ly8_rangeley_r0_BASEDIR)/module/src/make.mk
include $(x86_64_quanta_ly8_rangeley_r0_BASEDIR)/utest/_make.mk

