
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-07-07 19:11:57.261606
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
powerpc_quanta_lb9_r0_BASEDIR := $(BASEDIR)powerpc_quanta_lb9_r0
powerpc_quanta_ly2_r0_BASEDIR := $(BASEDIR)powerpc_quanta_ly2_r0


ALL_MODULES := $(ALL_MODULES) powerpc_quanta_lb9_r0 powerpc_quanta_ly2_r0
