
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2014-08-03 09:25:20.093307
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
eeprom_BASEDIR := $(BASEDIR)eeprom
powerpc_quanta_lb9_r0_BASEDIR := $(BASEDIR)powerpc_quanta_lb9_r0
powerpc_quanta_ly2_r0_BASEDIR := $(BASEDIR)powerpc_quanta_ly2_r0
quanta_sys_eeprom_BASEDIR := $(BASEDIR)quanta_sys_eeprom


ALL_MODULES := $(ALL_MODULES) eeprom powerpc_quanta_lb9_r0 powerpc_quanta_ly2_r0 quanta_sys_eeprom
