###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := powerpc_quanta_lb9_r0
AUTOMODULE := powerpc_quanta_lb9_r0
include $(BUILDER)/definemodule.mk
