
###############################################################################
#
# Inclusive Makefile for the powerpc_quanta_lb9_r0 module.
#
# Autogenerated 2014-10-15 17:33:54.325913
#
###############################################################################
powerpc_quanta_lb9_r0_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(powerpc_quanta_lb9_r0_BASEDIR)/module/make.mk
include $(powerpc_quanta_lb9_r0_BASEDIR)/module/auto/make.mk
include $(powerpc_quanta_lb9_r0_BASEDIR)/module/src/make.mk
include $(powerpc_quanta_lb9_r0_BASEDIR)/utest/_make.mk

