###############################################################################
#
# 
#
###############################################################################
include ../../init.mk
MODULE := powerpc_quanta_ly2_r0
AUTOMODULE := powerpc_quanta_ly2_r0
include $(BUILDER)/definemodule.mk
