
###############################################################################
#
# Inclusive Makefile for the powerpc_quanta_ly2_r0 module.
#
# Autogenerated 2014-07-07 07:35:34.537009
#
###############################################################################
powerpc_quanta_ly2_r0_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(powerpc_quanta_ly2_r0_BASEDIR)/module/make.mk
include $(powerpc_quanta_ly2_r0_BASEDIR)/module/auto/make.mk
include $(powerpc_quanta_ly2_r0_BASEDIR)/module/src/make.mk
include $(powerpc_quanta_ly2_r0_BASEDIR)/utest/_make.mk

